### PR TITLE
Navigation change + some refactored folder structure!

### PR DESCRIPTION
**Pull request by mdwagner**
**Highlights**
- Replaced [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) with [react-navigation](https://reactnavigation.org/), the successor to _ex-navigation_
- Moved all source files into _src_ folder
- Mapbox API wasn't working for me, but I got it to work the [_new way_](https://www.mapbox.com/help/define-matrix-api/) (they renamed the Distance API to the Matrix API). However, since it's still working on the App Store, I'm having it use the _new way_ when it's in development mode only.

Let me know if you have any questions/requests, I'd be happy to answer/do them!

### CODE REVIEW

**Comment by johnkeith** [comment]
That's a pretty good PR, @mdwagner. Where are the specs to prove this works and it does not go 💣 💥  in the future?

**Comment by brandonfancher** [comment]
@mdwagner: Awesome! Our first OSS contribution. Thank you!

We'll review this as soon as possible. I might need to get some of the Team Luna guys together, so be patient. 

Again, thanks!

**Comment by mdwagner** [comment]
Awesome. Also, I didn't make any tests yet because there currently aren't any, but I can add them. And I compared it to the current app to make sure the CSS is the same throughout the app, but please point out anything I missed (I tried to keep it look exactly the same).

**Comment by brandonfancher** [comment]
@mdwagner: Testing is definitely something we'd like to implement in this project, and all the more important as more people start contributing. If you have time and want to add some tests, that'd be awesome (but it's not a prerequisite yet.) By adding them here, you'd pretty much be setting the example/foundation for future tests, so it'd definitely be a big win.

**Comment by mdwagner** [comment]
@brandonfancher My only concern with adding tests here, is when I update all the dependencies the tests will probably fail. But yeah I can look into adding some tests, I do see the value in them moving forward. It's definitely on my list of things to do for this project (another is continuous integration with Travis-CI, so tests will be very important for that).

**Comment by mdwagner** [comment]
**UPDATE:** I am looking to get the original test passing at the moment.

**Comment by mdwagner** [comment]
**UPDATE 2:**
- After looking into jest testing and trying to get the original iOS `__tests__/index.ios.js` test passing (or even running), I determined it is out of the scope of this PR. When we update the React Native version, as well as the dependencies, we'll get access to the newest Jest (version 20 at this moment) which currently we're using Jest version 16. There ARE differences between those versions that, at this moment, I don't think is worth diving into, until after we upgrade.
- I removed the `__tests__` folder, because you can actually just have a `component.test.js` anywhere in the project and jest will pick it up.
- I added at least one test `AttributionButton.test.js` with a snapshot saved, so any future updates to that component will need to either match the snapshot or update it.
- I'm not going to add anymore tests for this PR, as adding one is just enough to get started, but future PR's will have more tests.
Thank you 🌟

**Comment by brandonfancher** [comment]
Thanks, @mdwagner. Make sense.

**Comment by brandonfancher** [comment]
Got if fired up locally in simulator. Working great. Changes look good. Only problem right now is that the station icons on the map aren't showing up for me. Probably something weird going on locally. So I'll troubleshoot that shortly. More than likely, it's something wrong with my setup and not the code. Will report back.

**Comment by brandonfancher** [comment]
I had to go into the assets in iTunes and rename `bluemarker` to `blueMarker` and `greenmarker` to `greenMarker`. Not sure why that changed. Again, prob some local issue, but I'm documenting it here so that we know what to look for/fix if it happens again.

**Pull request merged**
